/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

/**
 *
 * @author J-Michael
 */
public class BsCS extends javax.swing.JFrame {

    /**
     * Creates new form BsCrim
     */
    public BsCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerPanel = new javax.swing.JPanel();
        fourthBtn = new javax.swing.JButton();
        thirdBtn = new javax.swing.JButton();
        secondBtn = new javax.swing.JButton();
        firstBtn = new javax.swing.JButton();
        csSecLbl = new javax.swing.JLabel();
        cnameChecklbl = new javax.swing.JLabel();
        courseNameseclbl = new javax.swing.JLabel();
        courseTitle = new javax.swing.JLabel();
        courseNamelbl1 = new javax.swing.JLabel();
        courseNamelbl = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        bscsLbl = new javax.swing.JLabel();
        crimImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        innerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fourthBtn.setBackground(new java.awt.Color(0, 0, 0));
        fourthBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        fourthBtn.setForeground(new java.awt.Color(255, 255, 255));
        fourthBtn.setText("4th Year");
        innerPanel.add(fourthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 300, 70));

        thirdBtn.setBackground(new java.awt.Color(51, 51, 51));
        thirdBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        thirdBtn.setForeground(new java.awt.Color(255, 255, 255));
        thirdBtn.setText("3rd Year");
        innerPanel.add(thirdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 300, 70));

        secondBtn.setBackground(new java.awt.Color(51, 51, 51));
        secondBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        secondBtn.setForeground(new java.awt.Color(255, 255, 255));
        secondBtn.setText("2nd Year");
        innerPanel.add(secondBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 300, 70));

        firstBtn.setBackground(new java.awt.Color(0, 0, 0));
        firstBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        firstBtn.setForeground(new java.awt.Color(255, 255, 255));
        firstBtn.setText("1st Year");
        innerPanel.add(firstBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 300, 70));

        csSecLbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        csSecLbl.setForeground(new java.awt.Color(251, 176, 59));
        csSecLbl.setText("CS");
        innerPanel.add(csSecLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 50, 40));

        cnameChecklbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        cnameChecklbl.setForeground(new java.awt.Color(255, 255, 255));
        cnameChecklbl.setText("Check out the");
        innerPanel.add(cnameChecklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 240, 40));

        courseNameseclbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        courseNameseclbl.setForeground(new java.awt.Color(255, 255, 255));
        courseNameseclbl.setText(" Sections");
        innerPanel.add(courseNameseclbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, 160, 40));

        courseTitle.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        courseTitle.setForeground(new java.awt.Color(255, 255, 255));
        courseTitle.setText("BSCS SECTION");
        innerPanel.add(courseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 330, 50));

        courseNamelbl1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        courseNamelbl1.setForeground(new java.awt.Color(255, 255, 255));
        courseNamelbl1.setText("COMPUTER SCIENCE ");
        innerPanel.add(courseNamelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 370, 40));

        courseNamelbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        courseNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        courseNamelbl.setText("BACHELOR OF SCIENCE IN");
        innerPanel.add(courseNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 480, 50));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });
        innerPanel.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        homeLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(0, 0, 0));
        homeLbl.setText("Home >");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });
        innerPanel.add(homeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        courseLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(0, 0, 0));
        courseLbl.setText("Courses >");
        courseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseLblMouseClicked(evt);
            }
        });
        innerPanel.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        bscsLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bscsLbl.setForeground(new java.awt.Color(102, 0, 0));
        bscsLbl.setText("BSCS");
        innerPanel.add(bscsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 20));

        crimImage.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        crimImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BSCRIM.png"))); // NOI18N
        innerPanel.add(crimImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        FrameSwitch.showDashboard(this);
    }//GEN-LAST:event_homeLblMouseClicked

    private void courseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseLblMouseClicked
            FrameSwitch.showCoursePage(this);
    }//GEN-LAST:event_courseLblMouseClicked

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        Exit_Dialog dialog = new Exit_Dialog(this);
        if (dialog.showExitConfirmation()) {
            System.exit(0);
        };
    }//GEN-LAST:event_exitIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BsCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BsCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BsCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BsCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BsCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bscsLbl;
    private javax.swing.JLabel cnameChecklbl;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel courseNamelbl;
    private javax.swing.JLabel courseNamelbl1;
    private javax.swing.JLabel courseNameseclbl;
    private javax.swing.JLabel courseTitle;
    private javax.swing.JLabel crimImage;
    private javax.swing.JLabel csSecLbl;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JButton firstBtn;
    private javax.swing.JButton fourthBtn;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JButton secondBtn;
    private javax.swing.JButton thirdBtn;
    // End of variables declaration//GEN-END:variables
}
