/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import java.awt.Toolkit;

/**
 *
 * @author J-Michael
 */
public class Course extends javax.swing.JFrame {

    /**
     * Creates new form Sections
     */
    public Course() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/cvsuSLogo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerPanel = new javax.swing.JPanel();
        crimBtn = new javax.swing.JButton();
        itBtn = new javax.swing.JButton();
        hmBtn = new javax.swing.JButton();
        compsBtn = new javax.swing.JButton();
        educBtn = new javax.swing.JButton();
        phyBtn = new javax.swing.JButton();
        bmBtn = new javax.swing.JButton();
        courseTitle = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        courseImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course");
        setUndecorated(true);
        setResizable(false);

        innerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crimBtn.setBackground(new java.awt.Color(0, 0, 0));
        crimBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        crimBtn.setForeground(new java.awt.Color(255, 255, 255));
        crimBtn.setText("BSCRIM");
        crimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimBtnActionPerformed(evt);
            }
        });
        innerPanel.add(crimBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 170, 80));

        itBtn.setBackground(new java.awt.Color(0, 0, 0));
        itBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        itBtn.setForeground(new java.awt.Color(255, 255, 255));
        itBtn.setText("BSIT");
        itBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itBtnActionPerformed(evt);
            }
        });
        innerPanel.add(itBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 170, 80));

        hmBtn.setBackground(new java.awt.Color(0, 0, 0));
        hmBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        hmBtn.setForeground(new java.awt.Color(255, 255, 255));
        hmBtn.setText("BSHM");
        innerPanel.add(hmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 170, 80));

        compsBtn.setBackground(new java.awt.Color(0, 0, 0));
        compsBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        compsBtn.setForeground(new java.awt.Color(255, 255, 255));
        compsBtn.setText("BSCS");
        compsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compsBtnActionPerformed(evt);
            }
        });
        innerPanel.add(compsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 170, 80));

        educBtn.setBackground(new java.awt.Color(0, 0, 0));
        educBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        educBtn.setForeground(new java.awt.Color(255, 255, 255));
        educBtn.setText("BSED");
        innerPanel.add(educBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 170, 80));

        phyBtn.setBackground(new java.awt.Color(0, 0, 0));
        phyBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        phyBtn.setForeground(new java.awt.Color(255, 255, 255));
        phyBtn.setText("BSPHY");
        innerPanel.add(phyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 170, 80));

        bmBtn.setBackground(new java.awt.Color(0, 0, 0));
        bmBtn.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        bmBtn.setForeground(new java.awt.Color(255, 255, 255));
        bmBtn.setText("BSBM");
        innerPanel.add(bmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 170, 80));

        courseTitle.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        courseTitle.setForeground(new java.awt.Color(255, 255, 255));
        courseTitle.setText("Courses");
        innerPanel.add(courseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 180, 50));

        titleLabel.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Cavite State University - Bacoor");
        innerPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 360, 50));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });
        innerPanel.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        courseLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(0, 102, 0));
        courseLbl.setText("Courses");
        innerPanel.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 60, 60));

        homeLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(0, 0, 0));
        homeLbl.setText("Home >");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });
        innerPanel.add(homeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 90, 60, 60));

        courseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Course.png"))); // NOI18N
        innerPanel.add(courseImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        FrameSwitch.showDashboard(this);
    }//GEN-LAST:event_homeLblMouseClicked

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        Exit_Dialog dialog = new Exit_Dialog(this);
        if (dialog.showExitConfirmation()) {
            System.exit(0);
        };
    }//GEN-LAST:event_exitIconMouseClicked

    private void crimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimBtnActionPerformed

    }//GEN-LAST:event_crimBtnActionPerformed

    private void compsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compsBtnActionPerformed
        FrameSwitch.showBSCSPage(this);
    }//GEN-LAST:event_compsBtnActionPerformed

    private void itBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itBtnActionPerformed
        FrameSwitch.showBSITPage(this);
    }//GEN-LAST:event_itBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmBtn;
    private javax.swing.JButton compsBtn;
    private javax.swing.JLabel courseImg;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel courseTitle;
    private javax.swing.JButton crimBtn;
    private javax.swing.JButton educBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JButton hmBtn;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JButton itBtn;
    private javax.swing.JButton phyBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
