/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author J-Michael
 */
public class Old_Building_Fourthfloor extends javax.swing.JFrame {

    /**
     * Creates new form Old_Building_Firstfloor
     */
    public Old_Building_Fourthfloor() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/cvsuSLogo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerPanel = new javax.swing.JPanel();
        fourtFloorlbl = new javax.swing.JLabel();
        thirdFloorlbl = new javax.swing.JLabel();
        secondFloorlbl = new javax.swing.JLabel();
        firstFloorlbl = new javax.swing.JLabel();
        oldBuildingLbl = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        mapLbl = new javax.swing.JLabel();
        oldbuildingBtn = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        downimagebtn = new javax.swing.JLabel();
        fourthfloorImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        innerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fourtFloorlbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fourtFloorlbl.setForeground(new java.awt.Color(0, 102, 0));
        fourtFloorlbl.setText("4th Floor");
        fourtFloorlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourtFloorlblMouseClicked(evt);
            }
        });
        innerPanel.add(fourtFloorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 40));

        thirdFloorlbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        thirdFloorlbl.setForeground(new java.awt.Color(255, 255, 255));
        thirdFloorlbl.setText("3rd Floor >");
        thirdFloorlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdFloorlblMouseClicked(evt);
            }
        });
        innerPanel.add(thirdFloorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, 40));

        secondFloorlbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        secondFloorlbl.setForeground(new java.awt.Color(255, 255, 255));
        secondFloorlbl.setText("2nd Floor >");
        secondFloorlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondFloorlblMouseClicked(evt);
            }
        });
        innerPanel.add(secondFloorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 40));

        firstFloorlbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        firstFloorlbl.setForeground(new java.awt.Color(255, 255, 255));
        firstFloorlbl.setText("1st Floor >");
        firstFloorlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstFloorlblMouseClicked(evt);
            }
        });
        innerPanel.add(firstFloorlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 40));

        oldBuildingLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        oldBuildingLbl.setForeground(new java.awt.Color(255, 255, 255));
        oldBuildingLbl.setText("Old Building >");
        oldBuildingLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldBuildingLblMouseClicked(evt);
            }
        });
        innerPanel.add(oldBuildingLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 40));

        homeLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setText("Home >");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });
        innerPanel.add(homeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 40));

        mapLbl.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        mapLbl.setForeground(new java.awt.Color(255, 255, 255));
        mapLbl.setText("Map >");
        mapLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLblMouseClicked(evt);
            }
        });
        innerPanel.add(mapLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 40));

        oldbuildingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldbuildingBtnMouseClicked(evt);
            }
        });
        innerPanel.add(oldbuildingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 60, 130));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });
        innerPanel.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 40, 50));

        downimagebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downimagebtnMouseClicked(evt);
            }
        });
        innerPanel.add(downimagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 120, 170));

        fourthfloorImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OldbdFourthFloor.png"))); // NOI18N
        innerPanel.add(fourthfloorImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldbuildingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldbuildingBtnMouseClicked

    }//GEN-LAST:event_oldbuildingBtnMouseClicked

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        FrameSwitch.showDashboard(this);
    }//GEN-LAST:event_homeLblMouseClicked

    private void oldBuildingLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oldBuildingLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_oldBuildingLblMouseClicked

    private void firstFloorlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstFloorlblMouseClicked
        FrameSwitch.showOldFirstPage(this);
    }//GEN-LAST:event_firstFloorlblMouseClicked

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        Exit_Dialog dialog = new Exit_Dialog(this);
        if (dialog.showExitConfirmation()) {
            System.exit(0);
        };
    }//GEN-LAST:event_exitIconMouseClicked

    private void mapLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLblMouseClicked
        FrameSwitch.showMapPage(this);
    }//GEN-LAST:event_mapLblMouseClicked

    private void secondFloorlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondFloorlblMouseClicked
        FrameSwitch.showOldSecondPage(this);
    }//GEN-LAST:event_secondFloorlblMouseClicked

    private void thirdFloorlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdFloorlblMouseClicked
        FrameSwitch.showOldThirdPage(this);
    }//GEN-LAST:event_thirdFloorlblMouseClicked

    private void fourtFloorlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourtFloorlblMouseClicked
        JOptionPane.showMessageDialog(null, "You are Here! ");
    }//GEN-LAST:event_fourtFloorlblMouseClicked

    private void downimagebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downimagebtnMouseClicked
    FrameSwitch.showOldThirdPage(this);
    }//GEN-LAST:event_downimagebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Old_Building_Fourthfloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Old_Building_Fourthfloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Old_Building_Fourthfloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Old_Building_Fourthfloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Old_Building_Fourthfloor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel downimagebtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel firstFloorlbl;
    private javax.swing.JLabel fourtFloorlbl;
    private javax.swing.JLabel fourthfloorImg;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel mapLbl;
    private javax.swing.JLabel oldBuildingLbl;
    private javax.swing.JLabel oldbuildingBtn;
    private javax.swing.JLabel secondFloorlbl;
    private javax.swing.JLabel thirdFloorlbl;
    // End of variables declaration//GEN-END:variables
}
