/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import javax.swing.JOptionPane;

/**
 *
 * @author J-Michael
 */
public class View_Sched_IT extends javax.swing.JFrame {

    /**
     * Creates new form View_Sched_IT
     */
    public View_Sched_IT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerPanel = new javax.swing.JPanel();
        firstsemSchedImg = new javax.swing.JLabel();
        secondsemSchedConImg = new javax.swing.JLabel();
        sectionLbl = new javax.swing.JLabel();
        leftMaxbtn = new javax.swing.JLabel();
        leftOnebtn = new javax.swing.JLabel();
        rightOnebtn = new javax.swing.JLabel();
        rightMaxbtn = new javax.swing.JLabel();
        titleIt = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        ITlbl = new javax.swing.JLabel();
        bsitLbl = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        homebtnLabel = new javax.swing.JLabel();
        teacherbtnLabel = new javax.swing.JLabel();
        coursebtnLabel = new javax.swing.JLabel();
        mapbtnLabel = new javax.swing.JLabel();
        searchlbl = new javax.swing.JLabel();
        itSchedImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        innerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        innerPanel.add(firstsemSchedImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 370, 290));
        innerPanel.add(secondsemSchedConImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 370, 290));

        sectionLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        sectionLbl.setForeground(new java.awt.Color(0, 0, 0));
        sectionLbl.setText("BSIT 1-1");
        sectionLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sectionLblMouseClicked(evt);
            }
        });
        innerPanel.add(sectionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 150, 90));
        innerPanel.add(leftMaxbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 50, 60));
        innerPanel.add(leftOnebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 40, 60));
        innerPanel.add(rightOnebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 40, 60));
        innerPanel.add(rightMaxbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 50, 60));

        titleIt.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titleIt.setForeground(new java.awt.Color(255, 255, 255));
        titleIt.setText("IT SCHEDULE (1ST- 4TH YEAR) ");
        titleIt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleItMouseClicked(evt);
            }
        });
        innerPanel.add(titleIt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 740, 90));

        homeLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setText("Home >");
        homeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLblMouseClicked(evt);
            }
        });
        innerPanel.add(homeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 40));

        courseLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(255, 255, 255));
        courseLbl.setText("Courses >");
        courseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseLblMouseClicked(evt);
            }
        });
        innerPanel.add(courseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 40));

        ITlbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ITlbl.setForeground(new java.awt.Color(0, 255, 51));
        ITlbl.setText("View IT");
        innerPanel.add(ITlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 40));

        bsitLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bsitLbl.setForeground(new java.awt.Color(255, 255, 255));
        bsitLbl.setText("BSIT >");
        bsitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsitLblMouseClicked(evt);
            }
        });
        innerPanel.add(bsitLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 40));

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });
        innerPanel.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        homebtnLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        homebtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        homebtnLabel.setText("Home");
        homebtnLabel.setFocusable(false);
        homebtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnLabelMouseClicked(evt);
            }
        });
        innerPanel.add(homebtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, -1));

        teacherbtnLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        teacherbtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        teacherbtnLabel.setText("Teachers");
        teacherbtnLabel.setFocusable(false);
        teacherbtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherbtnLabelMouseClicked(evt);
            }
        });
        innerPanel.add(teacherbtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 40));

        coursebtnLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        coursebtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        coursebtnLabel.setText("Courses");
        coursebtnLabel.setFocusable(false);
        coursebtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursebtnLabelMouseClicked(evt);
            }
        });
        innerPanel.add(coursebtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, 120, 30));

        mapbtnLabel.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        mapbtnLabel.setForeground(new java.awt.Color(255, 255, 255));
        mapbtnLabel.setText("Map");
        mapbtnLabel.setFocusable(false);
        mapbtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapbtnLabelMouseClicked(evt);
            }
        });
        innerPanel.add(mapbtnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, 110, 30));

        searchlbl.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        searchlbl.setForeground(new java.awt.Color(255, 255, 255));
        searchlbl.setText("Search");
        searchlbl.setFocusable(false);
        innerPanel.add(searchlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 40));

        itSchedImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewITSCHED.png"))); // NOI18N
        innerPanel.add(itSchedImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        Exit_Dialog dialog = new Exit_Dialog(this);
        if (dialog.showExitConfirmation()) {
            System.exit(0);
        };
    }//GEN-LAST:event_exitIconMouseClicked

    private void homebtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnLabelMouseClicked
        FrameSwitch.showDashboard(this);
    }//GEN-LAST:event_homebtnLabelMouseClicked

    private void teacherbtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherbtnLabelMouseClicked
        JOptionPane.showMessageDialog(null, "You are Here! ");
    }//GEN-LAST:event_teacherbtnLabelMouseClicked

    private void coursebtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursebtnLabelMouseClicked
        FrameSwitch.showCoursePage(this);
    }//GEN-LAST:event_coursebtnLabelMouseClicked

    private void mapbtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapbtnLabelMouseClicked
        FrameSwitch.showMapPage(this);
    }//GEN-LAST:event_mapbtnLabelMouseClicked

    private void homeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLblMouseClicked
        FrameSwitch.showDashboard(this);
    }//GEN-LAST:event_homeLblMouseClicked

    private void courseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseLblMouseClicked
        FrameSwitch.showCoursePage(this);
    }//GEN-LAST:event_courseLblMouseClicked

    private void titleItMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleItMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_titleItMouseClicked

    private void sectionLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionLblMouseClicked

    private void bsitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsitLblMouseClicked
        FrameSwitch.showBSITPage(this);
    }//GEN-LAST:event_bsitLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Sched_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Sched_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Sched_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Sched_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Sched_IT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ITlbl;
    private javax.swing.JLabel bsitLbl;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel coursebtnLabel;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel firstsemSchedImg;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel homebtnLabel;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel itSchedImg;
    private javax.swing.JLabel leftMaxbtn;
    private javax.swing.JLabel leftOnebtn;
    private javax.swing.JLabel mapbtnLabel;
    private javax.swing.JLabel rightMaxbtn;
    private javax.swing.JLabel rightOnebtn;
    private javax.swing.JLabel searchlbl;
    private javax.swing.JLabel secondsemSchedConImg;
    private javax.swing.JLabel sectionLbl;
    private javax.swing.JLabel teacherbtnLabel;
    private javax.swing.JLabel titleIt;
    // End of variables declaration//GEN-END:variables
}
